hipchat: 
    token: null

google:
    private_key_id: null
    private_key: null
    client_email: null
    client_id: null
    type: "service_account"
    user: "your_user@your_email.com"

littlebits: 
    device: null
    token: null
